environment: "local"

postgres:
  enabled: false
  persistence:
    size: 1Gi
  env:
    POSTGRES_DB: "local-work-manager-db"
    POSTGRES_HOST: 'postgres-14-alpine'
    POSTGRES_PASSWORD: "root"
    POSTGRES_PORT: 5432
    POSTGRES_USER: "root"

net:
  host: "api.accelerator.test"

env:
  ALLOWED_ORIGINS: "http://localhost:4200, http://localhost:4201, http://agency.accelerator.test, http://public.accelerator.test, http://employer.accelerator.test"
  DB_CONNECTION_URL: "jdbc:postgresql://work-manager-postgres:5432/local-work-manager-db"
  DB_USERNAME: "root"
  DB_PASSWORD: "root"
  GCP_PROJECT_ID: "accelerator-dev-b6f2"
  CERBOS_URI: "127.0.0.1:3592" #"unix:/sock/cerbos.sock"
  SELF_SIGN_PUBLIC_KEY: "${sm://projects/accelerator-dev-b6f2/secrets/accelerator-self-signed-token-public-key/versions/latest}"
  SELF_SIGN_PRIVATE_KEY: "${sm://projects/accelerator-dev-b6f2/secrets/accelerator-self-signed-token-private-key/versions/latest}"
  USER_MANAGEMENT_BASE_URL: "http://user-management/um"
  TOKEN_PRIVATE_KEY_SECRET: "accelerator-self-signed-token-private-key"
  TOKEN_ISSUER: "accelerator"
  TOKEN_PRIVATE_KEY_VERSION: "latest"
  OTEL_SAMPLER_PROBABILITY: 1.0 # valid values: [0.0 - 1.0]
  DASHBOARD_URL: "http://public.accelerator.test/dashboard"
  PUBSUB_EMULATOR_HOST: "pubsub-emulator-service:8085" # set actual "host:port" to enable or false to disable
  PUBSUB_EMULATOR_ENABLED: true # set to true to enable emulator
  # accelerator-events publisher topics separated by comma
  PUBLISHER_TOPICS: projects/accelerator-dev-b6f2/topics/DOCUMENT_PROCESSING_INITIATION,projects/accelerator-dev-b6f2/topics/APPLICATION_ROLE_REPORTING,projects/accelerator-dev-b6f2/topics/NOTIFICATION_REQUESTS,projects/accelerator-dev-b6f2/topics/AUDIT_EVENTS_RECORDING
